part of localization;

/// Contains all keys that map to a localized value.
///
/// The keys on the localization map are accessed using it's corresponding
/// [AppLocalizationsKeys] property to enforce integrity.
class AppLocalizationsKeys {
  static const String usernameLabel = 'usernameLabel';
  static const String createEntryLabel = 'createEntryLabel';
  static const String emptyDiarySubtitle = 'emptyDiarySubtitle';
  static const String emptyDiaryBody = 'emptyDiaryBody';
  static const String personalizeLabel = 'personalizeLabel';
  static const String organizeLabel = 'organizeLabel';
  static const String browseDiaryTitle = 'browseDiaryTitle';
  static const String browseDiaryDesc = 'browseDiaryDesc';
  static const String reliveLabel = 'reliveLabel';
  static const String privateLabel = 'privateLabel';
  static const String readDiaryTitle = 'readDiaryTitle';
  static const String readDiaryDescr = 'readDiaryDescr';
  static const String privacyDescr = 'privacyDescr';
  static const String customizeBookmarkTitle = 'customizeBookmarkTitle';
  static const String customizeBookmarkDescr = 'customizeBookmarkDescr';
  static const String aboutAppDescr = 'aboutAppDescr';
  static const String inspiredByLabel = 'inspiredByLabel';
  static const String noFavoritesAvailLabel = 'noFavoritesAvailLabel';
  static const String noFavoritesAvailDescr = 'noFavoritesAvailDescr';
  static const String greetingLabel = 'greetingLabel';
  static const String welcomeBackLabel = 'welcomeBackLabel';
  static const String changeNameLabel = 'changeNameLabel';
  static const String changeYourNameLabel = 'changeYourNameLabel';
  static const String creatorDescr = 'creatorDescr';
  static const String detailsLabel = 'detailsLabel';
  static const String entrySavedDescr = 'entrySavedDescr';
  static const String untitledLabel = 'untitledLabel';
  static const String yourMoodLabel = 'yourMoodLabel';
  static const String noEntriesAvailLabel = 'noEntriesAvail';
  static const String diaryFallbackDescr = 'noEntriesAvailDescr';
  static const String statisticsFallbackDescr = 'statisticsFallbackDescr';
  static const String statisticsFallbackActionLabel =
      'statisticsFallbackActionLabel';
  static const String diaryEntriesLabel = 'diaryEntriesLabel';
  static const String avgMoodLabel = 'avgMoodLabel';
  static const String wordsWrittenLabel = 'wordsWrittenLabel';
  static const String wordsPerEntryLabel = 'wordsPerEntryLabel';
  static const String mostWordsAtOnceLabel = 'mostWordsAtOnceLabel';
  static const String fewestWordsAtOnceLabel = 'fewestWordsAtOnceLabel';
  static const String entriesThisWeekLabel = 'entriesThisWeekLabel';
  static const String entriesThisMonthLabel = 'entriesThisMonthLabel';
  static const String lastestEntryLabel = 'lastestEntryLabel';
  static const String firstEntryLabel = 'firstEntryLabel';
  static const String selectMainColorLabel = 'selectMainColorLabel';
  static const String selectAccentColorLabel = 'selectAccentColorLabel';
  static const String createLabel = 'createLabel';
  static const String stripesLabel = 'stripesLabel';
  static const String dotsLabel = 'dotsLabel';
  static const String mainColorLabel = 'mainColorLabel';
  static const String duplicateColorDescr = 'colorExistsDescr';
  static const String entryLabel = 'entryLabel';
  static const String entriesLabel = 'entriesLabel';
  static const String favoriteEntryLabel = 'favoriteEntryLabel';
  static const String favoriteEntriesLabel = 'favoriteEntriesLabel';
  static const String newDiaryTitle = 'newDiaryTitle';
  static const String newDiarySubtitle = 'newDiarySubtitle';
  static const String startJourneyTitle = 'startJourneyTitle';
  static const String diaryOfLabel = 'diaryOfLabel';
  static const String restoreDiaryTitle = 'restoreDiaryTitle';
  static const String continueJourneyTitle = 'continueJourneyTitle';
  static const String cancelRestoreDescr = 'cancelRestoreDescr';
  static const String backupFileRequiredTitle = 'backupFileRequiredTitle';
  static const String backupFileRequiredDescr = 'backupFileRequiredDescr';
  static const String storagePermissionDeniedTitle =
      'storagePermissionDeniedTitle';
  static const String storagePermissionDeniedDescr =
      'storagePermissionDeniedDescr';
  static const String requestPermissionLabel = 'requestPermissionLabel';
  static const String foundDiaryTitle = 'foundDiaryTitle';
  static const String lastEditedLabel = 'lastEditedLabel';
  static const String nextLabel = 'nextLabel';
  static const String previousLabel = 'previousLabel';
  static const String optionsLabel = 'optionsLabel';
  static const String firstLabel = 'firstLabel';
  static const String emptyEntryTitle = 'emptyEntryTitle';
  static const String emptyEntryDescr = 'emptyEntryDescr';
  static const String editLabel = 'editLabel';
  static const String emptyEntryActionDescr = 'emptyEntryActionDescr';
  static const String goodLabel = 'goodLabel';
  static const String badLabel = 'badLabel';
  static const String alrightLabel = 'alrightLabel';
  static const String quoteLabel = 'quoteLabel';
  static const String quoteSubtitle = 'quoteSubtitle';
  static const String byLabel = 'byLabel';
  static const String accentColorLabel = 'accentColor';
  static const String choosePhotoLabel = 'choosePhotoLabel';
  static const String alreadyAvailableLabel = 'alreadyAvailableLabel';
  static const String duplicateEntryDescr = 'duplicateEntryDescr';
  static const String duplicateEntryTodayDescr = 'duplicateEntryTodayDescr';
  static const String continueLabel = 'continueLabel';
  static const String yourNameLabel = 'yourNameLabel';
  static const String permissionsRequiredDescr = 'permissionsRequiredDescr';
  static const String backupInfoDescr = 'backupInfoDescr';
  static const String readingLabel = 'readingLabel';
  static const String noBackupFoundTitle = 'noBackupFoundTitle';
  static const String backupLabel = 'backupLabel';
  static const String noBackupFoundDescr = 'noBackupFoundDescr';
  static const String backupIdLabel = 'backupIdLabel';
  static const String lastestBackupLabel = 'lastestBackupLabel';
  static const String upToDateBackupDescr = 'upToDateBackupDescr';
  static const String deprecatedBackupDescr = 'deprecatedBackupDescr';
  static const String bookmarkSavedDescr = 'bookmarkSavedDescr';
  static const String homeLabel = 'homeLabel';
  static const String profileLabel = 'profileLabel';
  static const String mixedLabel = 'mixedLabel';
  static const String futureDateActionDescr = 'futureDateActionDescr';
  static const String futureDateDescr = 'futureDateDescr';
  static const String confirmDateLabel = 'confirmDateLabel';
  static const String hintText = 'hintText';
  static const String selectAnother = 'selectAnother';
}
